app:
  server:
    address: localhost
    port: 3000
    rate_limit:
      enabled: true
      max: 1000
      duration: 1m
    context:
      timeout: 1s
  login:
    timeout: 5s
  bypass_db: true

jwt:
  access:
    secret: secret_213455342425
    expiration: 6h
  refresh:
    secret: secret_345678654332453
    expiration: 12h

repository:
  user:
    store: postgres

database:
  mongo:
    host: mongodb
    port: 27017
    user: root
    password: example
    name: lagile
  postgres:
    host: 127.0.0.1
    port: 5432
    user: postgres
    password: postgres
    name: lagile
  redis:
    host: redis
    port: 6379
    password: redis